fix search config
FuelLabs/docs-hub pull request #14
Opened 2023-07-10 21:26 UTC by sarahschwartz

2023-07-11 11:26 UTC, luizstacio requested changes

2023-07-11 11:26 UTC, luizstacio commented on .github/workflows/docs-scrapper.yml
Do we need this CI yet?

2023-07-11 15:42 UTC, pedronauck requested changes
I guess the search results style needs some fixes

<img width="585" alt="CleanShot 2023-07-11 at 12 41 42@2x" src="https://github.com/FuelLabs/docs-hub/assets/2029172/d9ecf329-7097-4098-9b43-ac03a6e11985">

2023-07-11 16:05 UTC, sarahschwartz commented
> I guess the search results style needs some fixes
> 
> <img alt="CleanShot 2023-07-11 at 12 41 42@2x" width="585" src="https://user-images.githubusercontent.com/2029172/252717820-d9ecf329-7097-4098-9b43-ac03a6e11985.png">

yes, any keywords that are in the book titles right now look like this. Do you think we should just hide lvl0 results that are just matching with the book name? I noticed in our other books the h1 titles also show up like this right now too.

2023-07-14 18:33 UTC, pedronauck commented
@sarahschwartz checking other documentation like the on in NextJS, when searching they are showing the name of the page and also content in a nested style like that:
<img width="665" alt="CleanShot 2023-07-14 at 15 31 34@2x" src="https://github.com/FuelLabs/docs-hub/assets/2029172/8521dafe-2b6e-4274-9da0-a9c5dd65e49c">

this is very good to create this sense of navigation and search in the same time, but of course, this will need some level of customization right now... I guess that for the moment, we can go with just hiding the lv0 indeed

2023-07-19 13:09 UTC, pedronauck submitted a review, later dismissed

2023-07-19 21:22 UTC, luizstacio approved these changes

2023-07-19 21:25 UTC, merged