chore: change render system to SSG instead of SSR
FuelLabs/docs-hub pull request #22
Opened 2023-07-27 23:43 UTC by pedronauck

2023-07-28 19:19 UTC, sarahschwartz commented
Nice! The graphql recipes component is not rendering

2023-07-28 20:20 UTC, pedronauck commented
> Nice! The graphql recipes component is not rendering

thanks @sarahschwartz, now it's fixed 🙏🏻

2023-07-28 22:23 UTC, sarahschwartz approved these changes

2023-07-31 17:41 UTC, sarahschwartz requested changes
Can you carve out exceptions for fuel-hosted links that aren't in the docs hub like the block explorer? The block explorer link in the quickstart broke

2023-08-01 13:59 UTC, sarahschwartz approved these changes

2023-08-01 15:19 UTC, merged