chore: bump fuels-ts to 0.82.0
FuelLabs/docs-hub pull request #249
Opened 2024-04-25 17:54 UTC by sarahschwartz

2024-04-25 22:00 UTC, arboleya requested changes

2024-04-25 22:00 UTC, arboleya commented on docs/guides/docs/quickstart/building-a-frontend.mdx
> +- In your frontend directory, re-run this command: `npx fuels@0.67.0 typegen -i ../counter-contract/out/debug/*-abi.json -o ./src/contracts`
```suggestion
- In your frontend directory, re-run this command: `npx fuels@0.82.0 typegen -i ../counter-contract/out/debug/*-abi.json -o ./src/contracts`
```

2024-04-25 22:00 UTC, arboleya commented on docs/guides/examples/quickstart/frontend/package.json
> +    "fuels": "^0.82.0",
I think it should allow patches only, no?

```suggestion
    "fuels": "~0.82.0",
```

2024-04-26 13:46 UTC, sarahschwartz commented on docs/guides/docs/quickstart/building-a-frontend.mdx
> +- In your frontend directory, re-run this command: `npx fuels@0.67.0 typegen -i ../counter-contract/out/debug/*-abi.json -o ./src/contracts`
this is just for the beta-4 version

2024-04-26 13:47 UTC, arboleya approved these changes

2024-04-26 15:28 UTC, matt-user approved these changes

2024-04-26 15:30 UTC, merged