chore: update running a node docs for testnet
FuelLabs/docs-hub pull request #280
Opened 2024-05-22 19:31 UTC by matt-user

2024-05-22 20:29 UTC, calldelegation requested changes

2024-05-22 20:29 UTC, calldelegation commented on docs/guides/docs/running-a-node/running-a-testnet-node.mdx
> +--reserved-nodes /dns4/p2p-devnet.fuel.network/tcp/30333/p2p/16Uiu2HAm6pmJUedRFjennk4A8yWL6zCApHCuykzRRroqMjjxZ8o6  \
```suggestion
--reserved-nodes /dns4/p2p-devnet.fuel.network/tcp/30333/p2p/16Uiu2HAm6pmJUedRFjennk4A8yWL6zCApHCuykzRRroqMjjxZ8o6,/dns4/p2p-devnet.fuel.network/tcp/30334/p2p/16Uiu2HAm8dBwTRzqazCMqQDdR8thMa7BKiW4ep2B4DoQQp6Qhyfd  \
```

2024-05-22 20:29 UTC, calldelegation commented on docs/guides/docs/running-a-node/running-a-testnet-node.mdx
> +--reserved-nodes /dns4/p2p-devnet.fuel.network/tcp/30333/p2p/16Uiu2HAm6pmJUedRFjennk4A8yWL6zCApHCuykzRRroqMjjxZ8o6  \
Adding second reserve node as well

2024-05-22 20:36 UTC, sarahschwartz requested changes

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
>  To start the node with a custom configuration, you can use the command below:
this command is deprecated: 

```sh
forc deploy --unsigned --node-url 127.0.0.1:4000/graphql
```

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
>  To start the node with a custom configuration, you can use the command below:
This is outdated: "To modify the initial state of the chain, you must configure a `chainConfig.json` file."

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
>  To find an example chain configuration file for a specific `fuel-core` version, refer to the [`fuel-core`](https://github.com/FuelLabs/fuel-core/tree/v0.22.0/deployment/scripts/chainspec) repo.
I removed this temporarily, but can you add back the code import [here](https://docs.fuel.network/guides/running-a-node/running-a-local-node/#chain-configuration) to show all of the config files?

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
>  To find an example chain configuration file for a specific `fuel-core` version, refer to the [`fuel-core`](https://github.com/FuelLabs/fuel-core/tree/v0.22.0/deployment/scripts/chainspec) repo.
```suggestion
To find an example chain configuration file for a specific `fuel-core` version, refer to the [`fuel-core`](https://github.com/FuelLabs/fuel-core/tree/v0.26.0/bin/fuel-core/chainspec/testnet) repo.
```

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-testnet-node.mdx
> +<ConditionalContent versionSet={props.versionSet} showForVersions={["default"]}>
Can you remove the conditional content component so this shows for default and nightly?

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
>  To start the node, run the following command:
The section above need to be updated since the coins array is now inside the `state_config.json`

2024-05-22 20:36 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-testnet-node.mdx
>  <TextImport
Can you remove the part about Rust? I don't think it's required for this

2024-05-22 20:44 UTC, matt-user commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
>  To start the node with a custom configuration, you can use the command below:
what's the new command,  `forc-deploy`?

2024-05-22 23:04 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
> +forc deploy --default-signer --node-url 127.0.0.1:4000/graphql
it seems like this doesn't work ootb anymore, and the wallet has to be funded? probably worth noting here

2024-05-22 23:05 UTC, sarahschwartz commented on docs/guides/docs/running-a-node/running-a-local-node.mdx
> +  Here is the [specific configuration](https://github.com/FuelLabs/fuel-core/tree/v0.26.0/bin/fuel-core/chainspec/testnet)
something is happening to this link so it doesn't work in the preview 🤔

2024-05-24 14:39 UTC, sarahschwartz approved these changes

2024-05-24 14:41 UTC, merged