chore: update fuels-ts to 0.57.0
FuelLabs/docs-hub pull request #59
Opened 2023-09-20 17:16 UTC by sarahschwartz

2023-09-20 18:07 UTC, calldelegation commented on docs/guides/docs/quickstart/building-a-frontend.mdx
> +> Note: Make sure your browser is using the latest version of chromium.
Do we want to show them how to find their wallet version?

2023-09-21 20:52 UTC, luizstacio requested changes
The ts-sdk just released a new version `0.58.0` with a big break change from that is implemented on the wallet here: https://github.com/FuelLabs/fuels-wallet/pull/876

2023-09-21 20:57 UTC, sarahschwartz commented
> The ts-sdk just released a new version `0.58.0` with a big break change from that is implemented on the wallet here: [FuelLabs/fuels-wallet#876](https://github.com/FuelLabs/fuels-wallet/pull/876)

Thanks, we saw the release, but I think we should move forward with this version for now, and will follow up with another PR once Harry has the updated migration guide ready for 0.58.0.

2023-09-21 21:40 UTC, cold-briu approved these changes

2023-09-22 03:02 UTC, calldelegation approved these changes

2023-09-22 14:40 UTC, merged